image: node:10.2.1 # change to match your node version

cache:
  paths:
    - node_modules/

test:
  stage: test
  services:
    - postgres:latest
  variables:
    # Configure postgres service (https://hub.docker.com/_/postgres/)
    POSTGRES_HOST: postgres
    POSTGRES_DB: budget
    POSTGRES_USER: budget
    POSTGRES_PASSWORD: budget
  before_script:
    # Install PG client & import schema info
    - apt-get update && apt-get install -y postgresql-client libpq-dev
    - PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -h $POSTGRES_HOST -d $POSTGRES_DB -f sql/budget.sql
  script:
    - npm install
    - DB_HOST=$POSTGRES_PASSWORD DB_PORT=5432 DB_NAME=$POSTGRES_DB DB_USER=$POSTGRES_USER DB_PASSWORD=$POSTGRES_PASSWORD npm run test